# Notebook for translating gene names and preparing input files for Eflux2

In [1]:
import pandas as pd

In [2]:
#load gene translation
filename = "../data/lpd-to-opag.csv"
cols = ["lpd",'opag']
df=pd.read_csv(filename)

Make dic from csv using pandas:

In [3]:
dic = pd.Series.from_csv(filename, header=None,).to_dict()

Test that dictionary works on LPD gene names and gives of OPAG gene names:

In [4]:
dic['Pd630_LPD00286']

'OPAG_08074'

In [5]:
dic.update({'#VALUE!': '#VALUE!'})

In [6]:
df0 = pd.read_csv('../data/lpd-genes-from-transcripts.csv')
df_translated=df0.replace(dic)

In [7]:
df_translated.to_csv("../data/translation-done.csv")

Now lets make the transcript files for Eflux2

In [8]:
df_transcripts = pd.read_csv('../data/all-transcript-data.csv')

Let's get an overview of our transcript data

In [9]:
df_transcripts.describe()

,Sample01,Sample02,Sample03,Sample04,Sample05,Sample06,Sample07,Sample08,Sample09,Sample10,...,Sample45,Sample46,Sample47,Sample48,Sample49,Sample50,Sample51,Sample52,Sample53,Sample54
count,8.390000e+03,8.390000e+03,8.390000e+03,8.390000e+03,8.390000e+03,8.390000e+03,8390.000000,8390.000000,8390.000000,8390.000000,...,8.390000e+03,8.390000e+03,8.390000e+03,8.390000e+03,8.390000e+03,8.390000e+03,8.390000e+03,8390.000000,8390.000000,8390.000000
mean,2.334087e+03,2.412095e+03,2.369379e+03,2.144577e+03,2.151918e+03,2.078855e+03,1405.328216,1438.004427,1332.358333,1337.627724,...,1.423080e+03,1.593188e+03,1.519608e+03,1.500181e+03,1.475291e+03,1.679431e+03,1.317908e+03,1405.170093,1268.760371,1303.959299
std,2.852322e+04,3.120629e+04,2.995129e+04,2.376418e+04,2.873381e+04,2.611510e+04,11144.987209,11872.338945,10587.484212,10010.371041,...,1.584355e+04,1.374716e+04,1.724074e+04,1.656779e+04,1.471510e+04,1.508146e+04,1.602788e+04,11407.572722,11432.764573,9760.192822
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
25%,4.611021e+01,4.773088e+01,4.842254e+01,4.398329e+01,4.955022e+01,4.670871e+01,41.690473,43.082548,41.077362,40.493691,...,3.908073e+01,3.934473e+01,3.818004e+01,3.828850e+01,4.102723e+01,4.044641e+01,3.966803e+01,35.922777,35.319991,34.758003
50%,2.125568e+02,2.113796e+02,2.064329e+02,1.960922e+02,2.086325e+02,2.049464e+02,164.019098,165.280321,169.714366,176.266654,...,1.735644e+02,1.931469e+02,2.006483e+02,1.947720e+02,1.897509e+02,1.713651e+02,1.902262e+02,176.246123,171.554242,179.664607
75%,8.637230e+02,8.714296e+02,8.626857e+02,8.610341e+02,8.436577e+02,8.595832e+02,727.114762,720.457702,760.471697,765.509406,...,7.663846e+02,8.858526e+02,9.106346e+02,8.666936e+02,7.897742e+02,7.224474e+02,7.969667e+02,800.404367,800.586463,858.057602
max,1.513949e+06,1.910512e+06,1.870881e+06,1.819049e+06,2.203428e+06,2.117516e+06,895918.938500,950683.006200,873759.819300,776834.538300,...,1.371587e+06,1.079622e+06,1.502979e+06,1.390568e+06,1.220145e+06,1.180112e+06,1.408187e+06,892019.796300,952401.034500,793235.885000

In [10]:
#save all the transcript files for input into Eflux2
for i in list(df_transcripts):
    print('Saving transcript data for ',i)
    df_index = df_translated.copy(deep=True)
    df_final = pd.concat([df_index,df_transcripts], axis=1, ignore_index=False)
    df_final[['LPD',i]].to_csv(i+"_transcripts_for_eflux2.csv", index=False, header=False)

Saving transcript data for  Sample01
Saving transcript data for  Sample02
Saving transcript data for  Sample03
Saving transcript data for  Sample04
Saving transcript data for  Sample05
Saving transcript data for  Sample06
Saving transcript data for  Sample07
Saving transcript data for  Sample08
Saving transcript data for  Sample09
Saving transcript data for  Sample10
Saving transcript data for  Sample11
Saving transcript data for  Sample12
Saving transcript data for  Sample13
Saving transcript data for  Sample14
Saving transcript data for  Sample15
Saving transcript data for  Sample16
Saving transcript data for  Sample17
Saving transcript data for  Sample18
Saving transcript data for  Sample19
Saving transcript data for  Sample20
Saving transcript data for  Sample21
Saving transcript data for  Sample22
Saving transcript data for  Sample23
Saving transcript data for  Sample24
Saving transcript data for  Sample25
Saving transcript data for  Sample26
Saving transcript data for  Sample27
Saving transcript data for  Sample28
Saving transcript data for  Sample29
Saving transcript data for  Sample30
Saving transcript data for  Sample31
Saving transcript data for  Sample32
Saving transcript data for  Sample33
Saving transcript data for  Sample34
Saving transcript data for  Sample35
Saving transcript data for  Sample36
Saving transcript data for  Sample37
Saving transcript data for  Sample38
Saving transcript data for  Sample39
Saving transcript data for  Sample40
Saving transcript data for  Sample41
Saving transcript data for  Sample42
Saving transcript data for  Sample43
Saving transcript data for  Sample44
Saving transcript data for  Sample45
Saving transcript data for  Sample46
Saving transcript data for  Sample47
Saving transcript data for  Sample48
Saving transcript data for  Sample49
Saving transcript data for  Sample50
Saving transcript data for  Sample51
Saving transcript data for  Sample52
Saving transcript data for  Sample53
Saving transcript data for  Sample54

In [11]:
#This is what the output for Eflux2 looks like
df_final[['LPD',i]]

                 LPD      Sample54
0         OPAG_07542   1057.916120
1         OPAG_07543   2477.119651
2         OPAG_07544   1488.229988
3         OPAG_07545    407.794599
4         OPAG_07546    442.552602
5         OPAG_07547     72.453302
6         OPAG_07548     42.590792
7         OPAG_07549     55.808625
8         OPAG_07550  12507.985590
9         OPAG_09250   1548.444557
10        OPAG_07553    612.426222
11        OPAG_07554    442.552602
12        OPAG_07555    798.944520
13        OPAG_07556    700.055553
14        OPAG_07557  12720.939550
15        OPAG_07558   3589.865297
16    Pd630_LPD00018     44.059440
17    Pd630_LPD00019    108.190404
18        OPAG_07559    292.750504
19        OPAG_07560    383.317132
20        OPAG_07561    375.973892
21        OPAG_07562    338.768142
22        OPAG_07563   3429.293114
23        OPAG_07564   7130.286110
24        OPAG_07565    770.061109
25        OPAG_07566    342.194987
26        OPAG_07567   1265.974588
27        OPAG_07568    518.922298
28        OPAG_07569   1751.607532
29        OPAG_07570   5731.643651
...              ...           ...
8360      OPAG_00529   2281.299916
8361      OPAG_01312     23.008819
8362      OPAG_06934     37.695299
8363         #VALUE!    243.795570
8364      OPAG_06937    174.769114
8365      OPAG_06938     93.503924
8366      OPAG_06939    114.554545
8367      OPAG_06940    348.069579
8368      OPAG_06941    293.729603
8369      OPAG_06942     41.611694
8370      OPAG_09127    105.253108
8371      OPAG_09128     97.909868
8372      OPAG_06943     18.113326
8373      OPAG_06945     43.080342
8374      OPAG_06946     29.862510
8375      OPAG_06947     77.348795
8376      OPAG_06948     42.101243
8377      OPAG_06949    110.638150
8378      OPAG_06950    218.339005
8379      OPAG_06951     82.733838
8380      OPAG_06952     14.686480
8381      OPAG_06953     27.414763
8382      OPAG_06954     25.456566
8383      OPAG_06955     17.623776
8384      OPAG_06956     27.414763
8385      OPAG_06957     52.381779
8386         #VALUE!    647.184225
8387         #VALUE!    357.860566
8388         #VALUE!    192.392890
8389         #VALUE!      6.364141

[8390 rows x 2 columns]